name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npx prettier . --check

      - name: Check linting
        run: npx eslint --max-warnings 0 .

      - name: Check package on Mac
        run: npm run package -- --platform darwin

      - name: Check package on Windows
        run: npm run package -- --platform win32

      - name: Check package on Linux
        run: npm run package -- --platform win32
